Cloud testapp
Otus-DevOps-2021-11/avasyutina_infra pull request #3
Opened 2022-01-09 07:46 UTC by avasyutina

# Выполнено ДЗ №

 - [+ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Установлен YC CLI
- Создан инстанс
 - Установлены  Ruby и Bundler, mongodb
 - Задеплоено приложение http://62.84.113.170:9292/

## Как проверить работоспособность:
 -перейти по ссылке http://62.84.113.170:9292/

## PR checklist
 - [ +] Выставил label с номером домашнего задания
 - [ +] Выставил label с темой домашнего задания

2022-01-09 16:39 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Вам стоит обратить вниманием на результаты тестов, не все файлы исполняемые от сюда и часть дополнительных ошибок
ДЗ возвращаю на доработку

2022-01-10 09:37 UTC, mrgreyves requested changes
А что изменилось?

2022-01-10 09:39 UTC, avasyutina commented
Ничего. Повторный пулл ещё не отправляла. С тестами разбираюсь.

2022-01-11 05:48 UTC, avasyutina commented
День добрый)
Просьба проверить повторно. 
И прислать обещанный промокод)

2022-01-11 06:53 UTC, mrgreyves approved these changes
Здравствуйте!)
Немного странно повели тесты себя =)
Промокод закинул вам в лк
ДЗ принимаю ^_^

2022-01-11 08:01 UTC, merged